#!/usr/bin/env bash
# bootstrap-secrets.sh — prompt for sensitive values and write them to
# infra/aws/terraform.tfvars (gitignored). Run ONCE per environment, or
# whenever a secret rotates. Does NOT touch AWS directly.
#
# Prerequisites: openssl (for jwt auto-generation), write access to repo.
# Env vars: none (values are prompted interactively).
#
# -----------------------------------------------------------------------------
# IMPORTANT: This script writes sensitive values to infra/aws/terraform.tfvars
# which is gitignored. The terraform config (infra/aws/ssm.tf) owns all four
# SSM SecureString parameters declaratively — it reads these tfvars at apply
# time and writes to SSM as part of `terraform apply`. Do NOT also call
# `aws ssm put-parameter` from this script: doing so causes drift between
# terraform state and SSM, and breaks `terraform destroy`.
#
# DATABASE_URL and REDIS_URL are computed by terraform from the RDS and
# ElastiCache endpoints respectively — they are NOT prompted here.
# -----------------------------------------------------------------------------

set -euo pipefail
IFS=$'\n\t'

# Resolve repo root via git so the script works from any cwd.
REPO_ROOT="$(git rev-parse --show-toplevel)"
TFVARS_PATH="${REPO_ROOT}/infra/aws/terraform.tfvars"
TFVARS_DIR="$(dirname "${TFVARS_PATH}")"

printf '==> bootstrap-secrets.sh\n'
printf '==> Writing to: %s\n' "${TFVARS_PATH}"

if [[ ! -d "${TFVARS_DIR}" ]]; then
  printf '==> ERROR: %s does not exist. Create infra/aws/ first.\n' "${TFVARS_DIR}" >&2
  exit 1
fi

if [[ -f "${TFVARS_PATH}" ]]; then
  printf '==> WARNING: %s already exists.\n' "${TFVARS_PATH}"
  read -r -p "==> Overwrite? [y/N] " overwrite
  if [[ "${overwrite:-}" != "y" && "${overwrite:-}" != "Y" ]]; then
    printf '==> Aborted. Existing file untouched.\n'
    exit 0
  fi
fi

# --- db_password --------------------------------------------------------------
printf '\n==> [1/3] RDS master password (db_password)\n'
printf '    Must be >=8 chars. Avoid /, @, ", and spaces (RDS restrictions).\n'
read -r -s -p "    db_password: " DB_PASSWORD
printf '\n'
if [[ -z "${DB_PASSWORD}" ]]; then
  printf '==> ERROR: db_password cannot be empty.\n' >&2
  exit 1
fi
read -r -s -p "    confirm:     " DB_PASSWORD_CONFIRM
printf '\n'
if [[ "${DB_PASSWORD}" != "${DB_PASSWORD_CONFIRM}" ]]; then
  printf '==> ERROR: passwords do not match.\n' >&2
  exit 1
fi

# --- openrouter_api_key -------------------------------------------------------
printf '\n==> [2/3] OpenRouter API key (openrouter_api_key)\n'
printf '    Starts with "sk-or-v1-". Get one at https://openrouter.ai/keys\n'
read -r -s -p "    openrouter_api_key: " OPENROUTER_KEY
printf '\n'
if [[ -z "${OPENROUTER_KEY}" ]]; then
  printf '==> ERROR: openrouter_api_key cannot be empty.\n' >&2
  exit 1
fi

# --- jwt_secret ---------------------------------------------------------------
printf '\n==> [3/3] JWT signing secret (jwt_secret)\n'
read -r -p "    Auto-generate with openssl rand -hex 32? [Y/n] " auto_jwt
if [[ "${auto_jwt:-Y}" == "Y" || "${auto_jwt:-Y}" == "y" || -z "${auto_jwt:-}" ]]; then
  if ! command -v openssl >/dev/null 2>&1; then
    printf '==> ERROR: openssl not found; install it or paste a secret manually.\n' >&2
    exit 1
  fi
  JWT_SECRET="$(openssl rand -hex 32)"
  printf '==> Generated 64-char hex secret.\n'
else
  read -r -s -p "    jwt_secret: " JWT_SECRET
  printf '\n'
  if [[ -z "${JWT_SECRET}" ]]; then
    printf '==> ERROR: jwt_secret cannot be empty.\n' >&2
    exit 1
  fi
fi

# --- write tfvars -------------------------------------------------------------
# Escape backslashes, double quotes, AND dollar signs for HCL string literals.
# Dollar matters because `$` is HCL interpolation syntax — `${foo}` would be
# interpreted by terraform. Backslash and quote matter for the string wrapper.
escape_hcl() {
  # shellcheck disable=SC2001
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\$/$$/g'
}

DB_PASSWORD_ESC="$(escape_hcl "${DB_PASSWORD}")"
OPENROUTER_KEY_ESC="$(escape_hcl "${OPENROUTER_KEY}")"
JWT_SECRET_ESC="$(escape_hcl "${JWT_SECRET}")"

UMASK_PREV="$(umask)"
umask 077
# Quoted heredoc — no shell expansion. Values are pre-escaped above.
{
  printf '# terraform.tfvars — generated by scripts/aws/bootstrap-secrets.sh\n'
  printf '# DO NOT COMMIT. This file is gitignored via infra/aws/*.tfvars.\n'
  printf '# Re-run bootstrap-secrets.sh to rotate any value.\n\n'
  printf 'db_password        = "%s"\n' "${DB_PASSWORD_ESC}"
  printf 'openrouter_api_key = "%s"\n' "${OPENROUTER_KEY_ESC}"
  printf 'jwt_secret         = "%s"\n' "${JWT_SECRET_ESC}"
} > "${TFVARS_PATH}"
umask "${UMASK_PREV}"
unset DB_PASSWORD_ESC OPENROUTER_KEY_ESC JWT_SECRET_ESC

# Clear sensitive vars from the environment ASAP.
unset DB_PASSWORD DB_PASSWORD_CONFIRM OPENROUTER_KEY JWT_SECRET

printf '\n==> Wrote %s (mode 0600).\n' "${TFVARS_PATH}"
printf '==> Next: ./scripts/aws/deploy.sh\n'
